FROM gramineproject/gramine:1.8-jammy

RUN apt update && apt install -y \
    build-essential \
    libssl-dev \
    libclang-dev \
    pkg-config

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
